import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kaiburr Java Spring Boot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar bg-base-100">
          <a className="btn btn-ghost text-xl">Kaiburr Spring Boot Frontend</a>
        </div>
        <div className="flex h-full flex-col items-center justify-between p-12 space-y-4">
          {children}
        </div>
      </body>
    </html>
  );
}
